---
# tasks file for firewalld
- name: Install Firewalld
  yum: name=firewalld state=installed

- name: Cofiguring firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    zone: public
    state: enabled
  loop:
    - 3306/tcp
    - 80/tcp

- name: Reloading firewalld
  command: "firewall-cmd --reload"

- name: Start Firewalld
  systemd: name=firewalld state=started enabled=yes
